### ISSUE TITLE
Suggestion from author of one more grunt git plugin

### ISSUE THREAD

**Issue by ZuBB** [tandrewnichols/grunt-simple-git#1]
Hi there!

I am an author of "one more grunt git plugin" © ([grunt-git-them-all](https://github.com/ZuBB/grunt-git-them-all)) :)

I have to admit that your idea of converting options to cli options is fantastic. Also I think that you picked up better name for plugin "grunt-simple-git" (vs "grunt-git-them-all") and for task "git" (vs "gta").

Due to reasons above I mostly sure that it would be smart for me to stop development of my plugin and switch to yours one. Although have to notice that my plugin has several nice features that your lacks and I hope you would not mind to have them in "grunt-simple-git".

What do you think?

**Comment by tandrewnichols** [comment]
Which features are you thinking of? The "storeOutputTo" feature?

I'm actually in the process of adding a feature to [simple-cli](https://github.com/tandrewnichols/simple-cli), which this uses, that will allow passing functions that will handle stdout and stderr (independently . . . you can already do _some_ stuff with the `stdio` key). But it shouldn't be hard to include essentially a final callback that passes the entire command output. Then you could do something like:

``` js
finalCallback: function(data) {
  grunt.config.set('git', data);
}
```

I would be more in favor of something flexible like this than an option specifically for setting things on config.

**Comment by ZuBB** [comment]
> Which features are you thinking of? The "storeOutputTo" feature?

Yes, it is one of them.

I am OK with "finalCallback" & independent handlers for stdout and stderr as a replacement  for "storeOutputTo" & "postProcessOutput"

What I am really lack for now in your plugin is a [logging of final command](https://github.com/ZuBB/grunt-git-them-all/blob/master/tasks/gta.js#L37)  that is going to be invoked

As far as I understand "stdio" manages "stdout" and "stderr" but simultaneously. Am I right?

And "force" option most close to my "failOnError". isn't it?

**Comment by tandrewnichols** [comment]
Ok, I'll add a debug option to log the final command. That's straight-forward. Not sure I want that to be the default (happens every time) because I can imagine people not really wanting that. The stdio option is currently what's passed to child_process.spawn as `stdio`, so you can (in theory - I haven't tried these things) pass, e.g., `'inherit'`, or `[null, process.stdout, process.stderr]` or `false` to not pass `stdio` into spawn (and use the default). The new feature will allow something like:

``` js
stdout: function(data) {
  console.log(data.toString()); // But something useful
}
```

and will be attached to the child's stdout via:

``` js
child.stdout.on('data', options.stdout);
```

And yeah, `failOnError: true` is essentially the default, and you can pass `force: true` to turn that off.

**Comment by ZuBB** [comment]
> Not sure I want that to be the default (happens every time) because I can imagine people not really wanting that.

In my code that is shown only in verbose/debug mode. You can go same way

Will wait for analog of storeOutputTo/postProcessOutput

# 

Also I have several questions on rawArgs/cmd usage. Would it be OK to post them here?

**Comment by tandrewnichols** [comment]
Go for it.

**Comment by ZuBB** [comment]
you have next example in readme

```
    // 'git checkout master -- config/*.json'
    checkout: {
      cmd: 'checkout master',
      rawArgs: '-- config/*.json'
    }
```

I do know you or somebody else is using "rawArgs". Lets forget that about that line. Final command that will be run in this case is 'git checkout master'. 1st word (git) is name of the executable, 2nd is a git (sub)?command. Main question here is what is 3rd part? Of course it is a part of command. But I would call it argument. what is nice about your version of plugin is that you trying to split actual command into unique parts/items. Having each part separately increases maintainability of that code/object (versus "line" in my case).

How about converting "rawArgs" into (or adding separate) "args" option? i.e. example above should like this

```
    // 'git checkout master
    checkout: {
      cmd: 'checkout',
      args: 'master',
    }
```

btw. If I understand correctly what should do a "rawArgs", then value of this option should not contain "--". those chars should be added automatically when constructing command

**Comment by tandrewnichols** [comment]
Hey, sorry - I must've read this and just forgotten to respond. I thought I had, but I see now that I didn't.

`rawArgs` is specifically for things that would be difficult to parse programmatically (i.e. splitting on a space may not be reliable). So the example above runs `git checkout master -- config/*.json`, but more notably, it calls child_process.spawn like this:

``` js
var child = child_process.spawn('git', ['checkout', 'master', '-- config/*.json']);
```

There may not be a lot of use cases for `rawArgs`, and frankly, I haven't used that feature in a live project to know whether it actually works as I'd expect. But until such time as someone reports that it doesn't, I'm okay leaving it in there.

I don't agree that the "--" should be added automatically. For a pure git implementation, that might make sense, but the library behind this is actually [simple-cli](https://github.com/tandrewnichols/simple-cli), which is meant to be consumable as a wrapper for _any_ cli tool. The idea was to provide a catch-all mechanism for dealing with things that couldn't be parsed as easily as `cmd.split(' ')`. A better example would be something with quotes, like a json string or commit message, where splitting on space would be a mistake (because the entirety of the quoted string is one argument, even though it has spaces in it). I want to leave a way to do that.

But as an alternative, I could imagine adding (maybe not immediately, but at some point) a feature that let's consumers of the simple-cli pass in additional options that the consumer itself would handle via some function. So that a git wrapper could basically say, "Hey, when someone says `filepaths`, call this function and I'll return `"--"` plus the original arguments. (I feel like that explanation doesn't make a lot of sense, but in my mind, I see how it would work, at least from a consumer standpoint.)

I am actually not a big fan of the `cmd` option because it feels redundant to have to say `cmd: 'checkout master'` when the name of the task is "checkout". Unfortunately, there's not a real reliable way to know whether the target name is a sub-command or just an arbitrary name (for instance, if you have more than one target that performs the same sub-command). You could do `args` and `cmd` instead, but that doesn't feel like a gain to me. I'd be more likely, actually, to say that `args` should be the only option (and get rid of `cmd`) and that it should be an array (since that's how it will be passed to child_process).

**Comment by ZuBB** [comment]
Hi!

I am a quite busy for now. Will reply at the end of next week. Sorry for that

**Comment by tandrewnichols** [comment]
All these features (I _think_) were implemented in [version 1.0.0](https://github.com/tandrewnichols/grunt-simple-git/releases/tag/v1.0.0).

**Comment by ZuBB** [comment]
Hi @tandrewnichols!

I am sorry for so long period of silence but I get new job (in new city..). All that eats any free time that I have.

Last weekend I made a release of my software that is based om my version of git plugin for grunt. Now new release starts I and ought to go back to this question. I made a review of new documentation and have to admit that you did fantastic job! I am really impressed.

Although I have one notice to example below.

```
grunt.initConfig({
  git: {
    status: {
      options: {
        simple: {
          force: true
        }
      }
    }
  }
});
```

In example above there is key/value pair `simple: {}`. I look quickly into sources and did not find any special intent for it. To me it looks superfluous. I would delete it, but maybe you have really strong reason on doing that? If so please share it.

**Comment by tandrewnichols** [comment]
Stuff under `simple` are options for the library itself (as opposed to git), so you could conceivable have:

``` js
grunt.initConfig({
  git: {
    push: {
      options: {
        force: true,
        simple: {
          force: true
        }
      }
    }
  }
});
```

So that would mean: run `git push --force` (this is the `options.force` key) and if something goes wrong, don't fail the task chain (this is the `options.simple.force` key). It was easier (for me) to look in a single place for options to the library than to try to exclude all the possible options. Not to mention, some of them would have conflicted (like `force`, which is a legit option in git).

On the readme, all the options (toward the bottom) under the heading "Simple cli options" go under that "simple" key. I think I mentioned it briefly in one place, but maybe it's not clear enough.

**Comment by ZuBB** [comment]
Ah, that makes sense. Thanks for explanation.

**Comment by ZuBB** [comment]
fyi: http://git.io/bhMV

**Comment by tandrewnichols** [comment]
Thanks!
